type Quote {
    symbol: String!
    currency: String!
    shortName: String!
    longName: String!
    regularMarketPrice: Float!
    regularMarketChange: Float!
    regularMarketChangePercent: Float!
    logoUrl: String!
    updatedAt: String!
    fiftyTwoWeekLow: Float!
    fiftyTwoWeekHigh: Float!
    marketCap: Float!
    regularMarketVolume: Float!
    regularMarketOpen: Float!
    regularMarketDayHigh: Float!
    regularMarketDayLow: Float!
    regularMarketPreviousClose: Float!
}